language: cpp
compiler: gcc
sudo: required
dist: trusty

#before_install:
#  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq --assume-yes cmake libpulse-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # gcc
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      # PictureIt deps
      - g++-6
      - cmake
      - cmake-data
      - libfftw3-dev
      - libglm-dev
      # glfwPI deps
      - libpulse-dev
      - libx11-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./ ../ && make install
