sudo: required
dist: trusty

language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -qq --assume-yes cmake libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

before_script:
  - cd "$TRAVIS_BUILD_DIR"
  - git submodule update --init

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./ ../ && make install
