# Try to find the PulseAudio library
#
# Once done this will define:
#
#  PULSEAUDIOSIMPLE_FOUND - system has the PulseAudio library
#  PULSEAUDIOSIMPLE_INCLUDE_DIR - the PulseAudio include directory
#  PULSEAUDIOSIMPLE_LIBRARY - the libraries needed to use PulseAudio
#
# Copyright (c) 2008, Matthias Kretz, <kretz@kde.org>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

if (PULSEAUDIOSIMPLE_INCLUDE_DIR AND PULSEAUDIOSIMPLE_LIBRARY)
   # Already in cache, be silent
   set(PULSEAUDIOSIMPLE_FIND_QUIETLY TRUE)
endif (PULSEAUDIOSIMPLE_INCLUDE_DIR AND PULSEAUDIOSIMPLE_LIBRARY)

if (NOT WIN32)
   include(FindPkgConfig)
   pkg_check_modules(PULSEAUDIOSIMPLE libpulse-simple)
   if(PULSEAUDIOSIMPLE_FOUND)
      set(PULSEAUDIOSIMPLE_LIBRARY ${PULSEAUDIOSIMPLE_LIBRARIES} CACHE FILEPATH "Path to the PulseAudioSimple library")
      set(PULSEAUDIOSIMPLE_INCLUDE_DIR ${PULSEAUDIOSIMPLE_INCLUDEDIR} CACHE PATH "Path to the PulseAudioSimple includes")
   endif(PULSEAUDIOSIMPLE_FOUND)
endif (NOT WIN32)

if (NOT PULSEAUDIOSIMPLE_INCLUDE_DIR)
   FIND_PATH(PULSEAUDIOSIMPLE_INCLUDE_DIR pulse/simple.h)
endif (NOT PULSEAUDIOSIMPLE_INCLUDE_DIR)

if (NOT PULSEAUDIOSIMPLE_LIBRARY)
   FIND_LIBRARY(PULSEAUDIOSIMPLE_LIBRARY NAMES pulse)
endif (NOT PULSEAUDIOSIMPLE_LIBRARY)

if (PULSEAUDIOSIMPLE_INCLUDE_DIR AND PULSEAUDIOSIMPLE_LIBRARY)
   set(PULSEAUDIOSIMPLE_FOUND TRUE)
else (PULSEAUDIOSIMPLE_INCLUDE_DIR AND PULSEAUDIOSIMPLE_LIBRARY)
   set(PULSEAUDIOSIMPLE_FOUND FALSE)
endif (PULSEAUDIOSIMPLE_INCLUDE_DIR AND PULSEAUDIOSIMPLE_LIBRARY)

if (PULSEAUDIOSIMPLE_FOUND)
   if (NOT PULSEAUDIOSIMPLE_FIND_QUIETLY)
      message(STATUS "Found PulseAudio-Simple: ${PULSEAUDIOSIMPLE_LIBRARY}")
   endif (NOT PULSEAUDIOSIMPLE_FIND_QUIETLY)
else (PULSEAUDIOSIMPLE_FOUND)
   message(STATUS "Could NOT find PulseAudio-Simple")
endif (PULSEAUDIOSIMPLE_FOUND)
